/* AUTO-GENERATED by admin.html — PUBLIC site data. Safe to commit & deploy. */
/* Edit through admin.html (local only). Anything in this file becomes public. */
window.SITE_DATA = {
  "revisions": [
    [
      "0.3",
      "2026-06-12",
      "Restructured as a controlled document; IP vault expanded."
    ],
    [
      "0.2",
      "2026-04-02",
      "Added IP vault section, IPV-001/002 validated."
    ],
    [
      "0.1",
      "2026-02-10",
      "First internal draft."
    ]
  ],
  "projects": [],
  "vault": []
};
