/* AUTO-GENERATED by admin.html — PUBLIC site data. Safe to commit & deploy. */
/* Edit through admin.html (local only). Anything in this file becomes public. */
window.SITE_DATA = {
  "revisions": [
    ["0.3", "2026-06-12", "Restructured as a controlled document; IP vault expanded."],
    ["0.2", "2026-04-02", "Added IP vault section, IPV-001/002 validated."],
    ["0.1", "2026-02-10", "First internal draft."]
  ],
  "projects": [
    {
      "no": "001",
      "title": "Smart Bench PSU",
      "domain": "power / embedded",
      "status": "active",
      "updated": "2026-06",
      "details": "\n      <h5>Overview</h5>\n      <p>A linear bench power supply (0–30 V / 0–3 A) controlled by an STM32 with a rotary-encoder\n      and OLED interface. Setpoints via DAC; analog constant-voltage / constant-current loops do\n      the actual regulation.</p>\n      <h5>Progress</h5>\n      <ul>\n        <li><span class=\"mk x\">[x]</span>Analog regulation stage simulated in LTspice</li>\n        <li><span class=\"mk x\">[x]</span>Control PCB rev A schematic complete</li>\n        <li><span class=\"mk t\">[~]</span>Firmware: encoder UI + calibration routine</li>\n        <li><span class=\"mk\">[ ]</span>Enclosure and front panel</li>\n      </ul>\n      <h5>Notes</h5>\n      <p>Thermal design of the pass transistor stage is the hard part. Learned why\n      <code>star grounding</code> matters when an ADC shares a board with a power stage.</p>"
    },
    {
      "no": "002",
      "title": "Pathfinding Visualizer",
      "domain": "software",
      "status": "done",
      "updated": "2025-11",
      "details": "\n      <h5>Overview</h5>\n      <p>Browser app for visualizing Dijkstra, A* (Manhattan heuristic), BFS and DFS on a grid —\n      built to actually understand the differences instead of memorizing them. Includes maze\n      generation via recursive division and step-by-step animation.</p>\n      <h5>Post-mortem</h5>\n      <p>Would add bidirectional search and weighted terrain. The grid renderer should have been\n      a single canvas, not 2,000 divs.</p>"
    },
    {
      "no": "003",
      "title": "RC Filter Designer (CLI)",
      "domain": "software / dsp",
      "status": "draft",
      "updated": "2026-05",
      "details": "\n      <h5>Overview</h5>\n      <p>Python tool: give it a corner frequency and topology, it returns the closest\n      <code>E24</code> standard component values and plots magnitude/phase with matplotlib.</p>\n      <h5>Progress</h5>\n      <ul>\n        <li><span class=\"mk x\">[x]</span>1st-order RC low/high-pass</li>\n        <li><span class=\"mk x\">[x]</span>E-series quantization with error report</li>\n        <li><span class=\"mk t\">[~]</span>Sallen-Key 2nd-order stages</li>\n      </ul>"
    }
  ],
  "vault": [
    {
      "no": "IPV-001",
      "title": "Buck converter 5 V / 2 A",
      "rev": "B",
      "validated": "2026-03",
      "status": "done",
      "statusLabel": "TESTED",
      "details": "\n      <h5>Specification</h5>\n      <ul>\n        <li><span class=\"mk\">·</span>Input 7–24 V → output 5 V @ 2 A, synchronous</li>\n        <li><span class=\"mk\">·</span>Efficiency 92 % at full load, 24 V in</li>\n        <li><span class=\"mk\">·</span>Ripple &lt; 30 mVpp</li>\n      </ul>\n      <h5>Validation</h5>\n      <p>Load-step tested 0.2 A → 2 A; thermal-imaged at full load for one hour. Rev B fixed\n      feedback-trace noise found in rev A — the hot loop was fine, the sense line wasn't.</p>"
    },
    {
      "no": "IPV-002",
      "title": "Precision high-side current sense",
      "rev": "A",
      "validated": "2026-01",
      "status": "done",
      "statusLabel": "TESTED",
      "details": "\n      <h5>Specification</h5>\n      <ul>\n        <li><span class=\"mk\">·</span>0–3 A high-side, 10 mΩ shunt, amplified to 0–3.0 V</li>\n        <li><span class=\"mk\">·</span>±1 % accuracy after single-point calibration</li>\n        <li><span class=\"mk\">·</span>RC-filtered, ADC-ready output</li>\n      </ul>\n      <h5>Notes</h5>\n      <p>Kelvin connection on the shunt is mandatory — the first breadboard version taught me\n      that the hard way. Currently used inside project 001.</p>"
    },
    {
      "no": "IPV-003",
      "title": "USB-C 5 V power input front-end",
      "rev": "A (draft)",
      "validated": "—",
      "status": "draft",
      "statusLabel": "IN DESIGN",
      "details": "\n      <h5>Goal</h5>\n      <p>A drop-in schematic and layout snippet so every future board gets robust USB-C power\n      without re-deriving it: correct 5.1 kΩ CC pull-downs, TVS array, polyfuse,\n      reverse-polarity guard.</p>\n      <h5>Progress</h5>\n      <ul>\n        <li><span class=\"mk x\">[x]</span>Schematic complete</li>\n        <li><span class=\"mk t\">[~]</span>Layout snippet + DRC</li>\n        <li><span class=\"mk\">[ ]</span>Bench validation board</li>\n      </ul>"
    }
  ]
};
